[hyodol] Step8-2 미션입니다.
code-squad/TODO-BE pull request #10
Opened 2019-06-10 11:18 UTC by bestdevhyo1225

1. 기획서 및 설계도
2. 구현 코드 
같이 PR 보냅니다.

2019-06-11 07:09 UTC, honux77 requested changes
효돌 왠지 가입 후 로그인이 안 됩니다. 확인해 보세요.

2019-06-11 07:16 UTC, honux77 commented on member_server.js
> +            setTimeout(() => memberClient.write(fileManager.isMember()), 100);
이 부분은 왜 이렇게 했을까요??

2019-06-12 04:43 UTC, bestdevhyo1225 commented on member_server.js
> +            setTimeout(() => memberClient.write(fileManager.isMember()), 100);
여러가지 테스트를 해보다가 고쳐야 한다는 것을 잊어버렸습니다. 현재는 문제가 되는 부분을 수정한 상태이며, 코드를 다시 정리한 다음 push 하겠습니다!ㅎㅎ

2019-06-15 05:55 UTC, merged

2019-06-15 05:55 UTC, honux77 commented
수고하셨어요! 짝짝

2019-06-15 05:55 UTC, honux77 commented
수고하셨어요! 👍